package org.lunifera.christmastree.control;

import java.io.IOException;
import java.io.InputStream;
import java.net.URL;

import org.eclipse.paho.client.mqttv3.IMqttDeliveryToken;
import org.eclipse.paho.client.mqttv3.MqttCallback;
import org.eclipse.paho.client.mqttv3.MqttMessage;
import org.lunifera.christmastree.control.AbstractControllerComponent.CommandDelegate;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.MouseEvents;
import com.vaadin.server.ExternalResource;
import com.vaadin.server.StreamResource;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Video;

@SuppressWarnings("serial")
public class MobileControlComponent extends AbstractControllerComponent {

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public MobileControlComponent(CommandDelegate delegate) {
		super();
		this.delegate = delegate;
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	protected AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("1280px");
		mainLayout.setHeight("720px");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// title area
		ThemeResource resource = new ThemeResource("images/Title.png");
		Image title = new Image(" ", resource);
		title.setHeight("54px");
		title.setWidth("413px");
		mainLayout.addComponent(title, "top:11.0px;left:60.0px");

		Image image = new Image();
		image.setHeight("240px");
		image.setWidth("320px");
		image.setSource(new ExternalResource("http://192.168.0.108:8081/stream", "video/x-motion-jpeg"));
		mainLayout.addComponent(image, "top:70.0px;left:50.0px;");
		
		VerticalLayout vl = new VerticalLayout();
		vl.setHeight("250px");
		vl.setWidth("200px");
		mainLayout.addComponent(vl, "top:380.0px;left:135.0px;");
		contentLayout = buildContent();
		vl.addComponent(contentLayout);

		return mainLayout;
	}

	@SuppressWarnings("deprecation")
	protected GridLayout buildContent() {
		// common part: create layout
		contentLayout = new GridLayout();
		contentLayout.setImmediate(false);
		contentLayout.setMargin(false);
		contentLayout.setColumns(2);
		contentLayout.setRows(4);

		// button_off
		button_off = new Embedded(null, new ThemeResource("./images/off.png"));
		button_off.setImmediate(true);
		button_off.setWidth("-1px");
		button_off.setHeight("-1px");
		button_off.addClickListener(listener);
		button_off.setStyleName("xmas-button-off");
		contentLayout.addComponent(button_off, 0, 0);
		contentLayout.setComponentAlignment(button_off,  Alignment.MIDDLE_LEFT);

		// button_on
		button_on = new Embedded(null, new ThemeResource("./images/on.png"));
		button_on.setImmediate(true);
		button_on.setWidth("-1px");
		button_on.setHeight("-1px");
		button_on.addListener(listener);
		button_on.setStyleName("xmas-button-on");
		contentLayout.addComponent(button_on, 1, 0);
		contentLayout.setComponentAlignment(button_on, Alignment.MIDDLE_RIGHT);

		// button_red
		button_red = new Embedded(null, new ThemeResource("./images/red.png"));
		button_red.setCaption("red");
		button_red.setImmediate(true);
		button_red.setWidth("-1px");
		button_red.setHeight("-1px");
		button_red.addListener(listener);
		button_red.setStyleName("xmas-button-red");
		contentLayout.addComponent(button_red, 0, 1);
		contentLayout.setComponentAlignment(button_red, Alignment.MIDDLE_LEFT);

		// button_blue
		button_blue = new Embedded(null, new ThemeResource("./images/blue.png"));
		button_blue.setCaption("blue");
		button_blue.setImmediate(true);
		button_blue.setWidth("-1px");
		button_blue.setHeight("-1px");
		button_blue.setStyleName("xmas-button-blue");
		button_blue.addListener(listener);
		contentLayout.addComponent(button_blue, 1, 1);
		contentLayout.setComponentAlignment(button_blue, Alignment.MIDDLE_RIGHT);

		// button_flash
		button_flash = new Embedded(null, new ThemeResource("./images/flash.png"));
		button_flash.setCaption("FLASH");
		button_flash.setImmediate(true);
		button_flash.setWidth("-1px");
		button_flash.setHeight("-1px");
		button_flash.addListener(listener);
		button_flash.setStyleName("xmas-button-flash");
		contentLayout.addComponent(button_flash, 0, 2);
		contentLayout.setComponentAlignment(button_flash, Alignment.MIDDLE_LEFT);

		// button_strobe
		button_strobe = new Embedded(null, new ThemeResource("./images/strobe.png"));
		button_strobe.setCaption("STROBO");
		button_strobe.setImmediate(true);
		button_strobe.setWidth("-1px");
		button_strobe.setHeight("-1px");
		button_strobe.addListener(listener);
		button_strobe.setStyleName("xmas-button-strobe");
		contentLayout.addComponent(button_strobe, 1, 2);
		contentLayout.setComponentAlignment(button_strobe, Alignment.MIDDLE_RIGHT);

		// button_snow
		button_snow = new Embedded(null, new ThemeResource("./images/snowflake.png"));
		button_snow.setCaption("Let it snow");
		button_snow.setImmediate(true);
		button_snow.setWidth("-1px");
		button_snow.setHeight("-1px");
		button_snow.addListener(listener);
		button_snow.setStyleName("xmas-button-snow");
		contentLayout.addComponent(button_snow, 0, 3);
		contentLayout.setComponentAlignment(button_snow, Alignment.MIDDLE_LEFT);

		// button_angel
		button_angel = new Embedded(null, new ThemeResource("./images/angel.png"));
		button_angel.setCaption("Angel");
		button_angel.setImmediate(true);
		button_angel.setWidth("-1px");
		button_angel.setHeight("-1px");
		button_angel.addListener(listener);
		button_angel.setStyleName("xmas-button-angel");
		contentLayout.addComponent(button_angel, 1, 3);
		contentLayout.setComponentAlignment(button_angel, Alignment.MIDDLE_RIGHT);

		return contentLayout;
	}

}
